### PR TITLE
Mason Altar Repair Tool

### PR DESCRIPTION
**Pull request by Wunarg**
Adds a tool to the mason altar (250 stone + 1 gas extractor) which allows you to repair stone blocks at range using stone
(turns damaged stone tiles into fixed stone tiles at the cost of 1 stone, works with stone backgrounds, also fixed mossy stone)
base range is 6 + squareroot(mason power /100) aka when you would have 100% chance to get mats back when placing blocks the range is 6 + (10) = 16

### CODE REVIEW

**Comment by Jim-Smiff** [comment]
I like these changes, I support

**Comment by laikadoggirl** [comment]
I think instead, the mason altar should have a field like the Ivan altar, which repairs stone around it, and can be expanded by donating stone or some shit

**Comment by laikadoggirl** [comment]
mobile remote repair is kinda retarded

**Comment by Wunarg** [comment]
Automatic repair field would have to be very small (which goes against the whole style) or very rare to active since checking and setting tiles is quite lag expensive, 
additionally mobile repair should be fine since its mostly usefull for fixing stone where you cant otherwise reach it such as in big stone walls or if you want to do it faster. Of course it could be used to repair things mid battle, but considering you need to build an entire altar and a lot of weapons effective against stone kill at least some stone in one shot (mostly explosives), it should be fine.

**Comment by laikadoggirl** [comment]
I dont know, as rain does the exact same shit in reverse, and doesnt lag too much, and it does it for the whole map

**Comment by laikadoggirl** [comment]
I feel like hand held could probably be good too, it would just need to have a balanced repair speed

**Comment by jammer312** [comment]
Checking tiles is quite cheap, and even cheaper if you use some data structure to store damaged repairable tiles and use it instead of iterating over CMap array.
Setting tiles one by one is network expensive, but it might or might not be possible to set tiles clientside-only, in which case it can get really cheap (for example, you could send coords + 10 bytes to provide bitmap for 9x9 area which determines which tiles in this area to repair).
You could go in a different direction and introduce fortifying field instead of repair one, which would be both more useful and less lag-generating.

**Comment by Gingerbeard5773** [comment]
I was thinking that it would be cheap to just choose only one random tile in a certain area every tick without a nested for loop, so you wouldn't have the expensive cost of checking every single tile and only ever check one. Also keep in mind that the tick speed would be slow.

**Comment by Gingerbeard5773** [comment]
https://user-images.githubusercontent.com/68350259/120943553-dc90f100-c6ec-11eb-888a-0b975ebed105.mp4

Here is what my method looks like. It checks for a random block and then repairs it. Range and check amounts depend on the altar's power. It is very efficient and will likely never cause any lag at all even with a large area to check.

**Comment by laikadoggirl** [comment]
F

**Pull request closed without merging**
