### PR TITLE
Territory Control: Manufacturing Badgers

### PR DESCRIPTION
**Pull request by laikadoggirl**
saw people complaining about assembler's stupidly high prices, looked for myself and yeah they were stupidly high

hopefully this incentivizes assembly rather than just buying shit with coins

full(ish) changelog
_I cannot be held liable for not included items_
-coal mine prices of dirt and copper reduced
dirt was kind expensive and who uses dirt
copper was stupidly expensive (4x the price of iron) as a tactic to nerf gauss spam which was changed anyway
-coal mine copper rate increased
yet again an aging nerf because there was never any use for copper, now there is
-all gun recipes buffed, no longer require steel
-bullet recipe yields buffed to be closer to viable, may need more tweaking
-cycled out the guided missile since its buggy as shit 
-cycled in the real frag grenade and shotgun
-created a sulfur recipe
-doubled assembler buffer size, assembler more things
-cost tweaks mostly to due with sulfur or copper costs

-oh and I also re-sorted the assembler

### CODE REVIEW

**Comment by xcs011** [comment]
oh and I also re-sorted the assembler

**Comment by laikadoggirl** [comment]
possibly coming soon:tm: I rewrite the assembler to be like any normal shop and not shitcoded with hardcoded icons, thatll be in a different pr though

**Comment by xcs011** [comment]
upon further reflection bullets may need an even greater yield change to be closer to as viable as the gunshop

**Comment by xcs011** [comment]
nah bullet yields are fine where they are

**Pull request merged**
