### PR TITLE
Slavery Return

### PR DESCRIPTION
**Pull request by Gingerbeard5773**
Readds Slavery into TC as per request of many players.
- Shackles are added back to the armory.
- After being slaved for **one and a half minutes** suicide is enabled.

### CODE REVIEW

**Comment by laikadoggirl** [comment]
suicide enabling is retarded though, give them some way to escape like ss13, where they only can when not being moved, it would still allow for people to escape if their overlords dont give them something to do, or put them in a box

**Comment by laikadoggirl** [comment]
literally just when not in motion the timer activates, gets reset upon motion, and make it 45 seconds instead

**Comment by laikadoggirl** [comment]
just throw up a bar over their player or something to illustrate it

**Comment by Blav2** [comment]
xcs011 is spitting fax no printer, @Gingerbeard5773  be like this kid

**Comment by Vam-Jam** [comment]
> literally just when not in motion the timer activates, gets reset upon motion, and make it 45 seconds instead

Except this can be easily abused and automated.

You could probably increase the timer to 5 mins, and give the player a 2/3 min cooldown on being slaved.

**Comment by asperger-sind** [comment]
What if
The player gets babbied and can't suicide?

**Comment by laikadoggirl** [comment]
> 
> 
> What if
> The player gets babbied and can't suicide?

then you are doing it right

**Comment by Gingerbeard5773** [comment]
Set this pull request to draft since there should be more work on this. I am setting this aside for now.

**Pull request closed without merging**
