### PR TITLE
Explosion lag

### PR DESCRIPTION
**Pull request by TC-DarkSlayer**
- Explosions had a million particles that are pretty much invisible to the naked human eye
- Shakes my screen for no reason shake my head
- can now throw meteor in grinder for mats

### CODE REVIEW

**Comment by laikadoggirl** [comment]
screen shake confirmed funny feature

**Comment by TC-DarkSlayer** [comment]
was fun back then when we kept throwing bombs at some noob and shook his screen then left the game with PTSD

**Comment by Vam-Jam** [comment]
I recommend you add a way to allow users to toggle screen shaking instead of removing them when you feel like it.

**Comment by Vam-Jam** [comment]
``Explosions had a million particles that are pretty much invisible to the naked human eye``
You out right remove fire on most of these bombs, which deal most the damage afterwards or cause more damage later on.

**Pull request closed without merging**
