### PR TITLE
Small Tweaks Nobody Asked For

### PR DESCRIPTION
**Pull request by TC-DarkSlayer**
- Building druglab has 1/3 chance of giving you a chemistry blueprint
- Placing backwall gives a little bit of coins
- Cook wood for coal at forge
- Sorted TinkerTable
- Engineer tools can be bought from tinkertable
- Can buy keg at buildershop (intended for armor)
- Dirt no longer takes the same hits as concrete from bullets
- RoyalGuards can now, but barely gain swim speed from flippers
- Player chickens can prime and throw fraggrenades
- Can order frag grenades via phone
- KudzuCores costs 5 mithril ingot
- Knockback from shotguns reduced by 30% to prevent flying
- ChickenStronghold/Citadel now has reduced max hp
- Royal armor stored in armory
- Added Library
- Library allows you to buy and sell blueprints
- Maps:
- Fixed falling ironplatforms when loading in maps
- Now have ironplatforms of different angles

### CODE REVIEW

**Comment by laikadoggirl** [comment]
Comment was lost when you split the monolithic pr, but the shotgun knockback reduction is no longer needed to prevent flying, as that was fixed with the 4x bullet glitch

**Comment by laikadoggirl** [comment]
Dark remove callahan from crafting it is LITERALLY the aimbot gun, and unironically even worse than the swaglag altar counterpart

**Comment by laikadoggirl** [comment]
The oof is also a little overpowered to be craftable, it will let whoever seizes the antimatter just instantly wins, even more so than having space tech

**Comment by TC-DarkSlayer** [comment]
Yeah it seems that callahan damage is pretty strong even with armor. (Even though it's a really fun weapon)
Oof yeah it's pretty broken (wished it shot something else like explodium)

**Comment by TC-DarkSlayer** [comment]
I'm probably going to have to split this pr again

**Pull request closed without merging**
