### PR TITLE
Tea

### PR DESCRIPTION
**Pull request by laikadoggirl**
**Removes drug effects**
Possibility of using a dart gun to counter currently op and stupidly broken drug meta, just shoot the drug royal knight with this and neutralize his current drugs, then kill him normally

Nugget did sprites again

### CODE REVIEW

**Comment by laikadoggirl** [comment]
This shit aint done yet

**Comment by xcs011** [comment]
Ok its done now

**Comment by Gingerbeard5773** [comment]
Sorry that I was not available, but now that I am I will let you know that I did make a tea 'drug' already before and that it has been on standby. Ping me and we can figure out how to improve this further.

**Comment by laikadoggirl** [comment]
For those who didn't see the conversation in discord, ginger pretty much has it covered, however this pr will remain open incase he wants to use the tea plant itself for something.

**Comment by laikadoggirl** [comment]
I had never actually got around to making all the drug scripts clean themselves up anyway

**Comment by Vam-Jam** [comment]
Closing due to tea being merged in already.

**Pull request closed without merging**
