### PR TITLE
Territory Control: Cartography Badgers

### PR DESCRIPTION
**Pull request by laikadoggirl**
Updated map icons with touched up versions of skem's

### CODE REVIEW

**Comment by laikadoggirl** [comment]
MinimapIcons
attached for reference
(they are literally just skems but not weirdly desaturated)

**Comment by laikadoggirl** [comment]
Do not merge this just yet, skem's icons need further touching up, they do not take to color changing well

**Comment by laikadoggirl** [comment]
Still needs sheet fixes, but then it is good to go

**Comment by Pirate-Rob** [comment]
Doesn't show up on github desktop whyyyy

**Pull request merged**
