### PR TITLE
Dark drugs

### PR DESCRIPTION
**Pull request by TC-DarkSlayer**
- Crak has significantly less damage reduction
- Crak gives less speed than before
- Domino gives less speed than before
- Fumes, Dew, and Domino lasts a bit longer
- Foof and Poot AoE is capped
- Reduced screenshake from foof
- Babbyed players can suicide after 1 min
- If you pax somone more than 2 times in a row, they will soon die from overdose
- Acid damages dirt but doesn't fully destroy it,
- FireGas(blaze) can now destroy castle blocks
- Druglab gives a bit more domino/fuel for dangerousDomino recipe

### CODE REVIEW

**Comment by laikadoggirl** [comment]
Bro you wouldnt have to deal with merge conflicts if you didnt lie to me about your changes originally

**Comment by laikadoggirl** [comment]
Bruh

**Comment by laikadoggirl** [comment]
Ye bro its a well known fact pcp actually reduces the damage small caliber arms do to your skin

**Comment by TC-DarkSlayer** [comment]
It was voted in #votes for the bullet nerf

**Comment by laikadoggirl** [comment]
Did not ask will make revert pr after

**Comment by laikadoggirl** [comment]
Pistols are okay I guess gameplay wise, shotguns is a bruh moment

**Comment by TC-DarkSlayer** [comment]
good luck getting vamist to accept a pr that goes against #votes

**Comment by laikadoggirl** [comment]
Good luck with merge conflicts 🤣

**Comment by TC-DarkSlayer** [comment]
tho ye prob didnt have to nerf shotguns havent used it in gameplay much besides autoshotgun that kills everything

**Comment by laikadoggirl** [comment]
Ye the pumpy has been not shit since gun rework and I'd rather keep it that way

**Comment by laikadoggirl** [comment]
It used to be hot ass

**Comment by laikadoggirl** [comment]
And even for pistols it's a fat why tho moment, nobody uses them anyway, why nerf them further

**Comment by TC-DarkSlayer** [comment]
Do you think the alien guns should use mithril ingots instead of mithril?

**Comment by laikadoggirl** [comment]
> Do you think the alien guns should use mithril ingots instead of mithril?

I forget can the fabricator make ingots

**Comment by TC-DarkSlayer** [comment]
low cal ammo/bobby guns people kept complaining how early game bobbygun just shreds

**Comment by TC-DarkSlayer** [comment]
Fabricator makes 2 mithril ingots with 10 mithril + 10 technicolor dust

**Comment by laikadoggirl** [comment]
> low cal ammo/bobby guns people kept complaining how early game bobbygun just shreds

There is so much less ass ways to decrease damage now than a sweeping change though, gun rework made it ez to just change the bobbygun

**Comment by laikadoggirl** [comment]
> Fabricator makes 2 mithril ingots with 10 mithril + 10 technicolor dust

I'd go with no, since it already requires you to have made or captured a fab, and they are easy as hell to make anyway. It wouldn't even nerf them, it would just make it tedious

**Comment by TC-DarkSlayer** [comment]
it'd reduce the ammo people have by 80%* that's a nerf in my book

**Comment by laikadoggirl** [comment]
Yeah but it's easy as hell to transmute more with the fab

**Comment by laikadoggirl** [comment]
Also you never added gatling ammo to the hitters exception for rifle, kinda sus bro

**Comment by TC-DarkSlayer** [comment]
also most low cal guns are actually pretty op
PDW, bobbygun, revolver actually kills sohkyo engineer in 1 sec, fugar pistol I haven't seen much, beagle should be rifle ammo imo, etc
PS gatling ammo uses rifle bulletType dmg

**Comment by laikadoggirl** [comment]
Pdw is meant to be, it's a chicken gun, revolver is bad cannot convince me otherwise, and even so, changing gun damages would take longer, but be so much less aids for any future dev

Beagle is a funny idea though

**Comment by TC-DarkSlayer** [comment]
pdws are like 3x better than assaultrifles

ye I think beagles using rifle ammo is funny not a gun expert(since im cali) but I think desert eagle uses stronger bullets than most pistols

**Comment by laikadoggirl** [comment]
> pdws are like 3x better than assaultrifles
> 
> ye I think beagles using rifle ammo is funny not a gun expert(since im cali) but I think desert eagle uses stronger bullets than most pistols

https://www.americanrifleman.org/content/desert-eagle-50-ae-the-semi-automatic-50-cal-handgun/
🤣

**Comment by laikadoggirl** [comment]
At this rate I'd just go with unnerf shotguns, go ham on the lights, and please just change their individual damages

**Comment by laikadoggirl** [comment]
Also for the love of God reduce the sar's recoil, I would use a fucking taser before it

**Comment by TC-DarkSlayer** [comment]
ye I panicked since vamist started doing github I literally jumped out of bed just now

ye im reducing sar recoil I'd rather throw them into the grinder

**Comment by laikadoggirl** [comment]
In bed at 1:55pm smh my head

**Comment by laikadoggirl** [comment]
But ye I'd rather shotgun not go back to the pre gun nerf days, otherwise the light nerf seems kinda based I guess

**Comment by TC-DarkSlayer** [comment]
would've woke up at 6 pm if it werent for uni

**Comment by TC-DarkSlayer** [comment]
ye im not touching shotgun since i never used it besides boom stick murderhobo days

**Comment by laikadoggirl** [comment]
Ye but it has no exception from fleshhit

**Comment by TC-DarkSlayer** [comment]
did you know shotguns deal 90% less dmg to metal some reason

meaning royalguards = hehehe

**Comment by laikadoggirl** [comment]
Aids

**Comment by laikadoggirl** [comment]
Also do you wanna finish zeppelin for me?

**Comment by TC-DarkSlayer** [comment]
no make mcsaucy suffer

**Comment by laikadoggirl** [comment]
> no make mcsaucy suffer

Lol

**Comment by TC-DarkSlayer** [comment]
SAR had about 1.8x the recoil of assaultrifle

**Comment by laikadoggirl** [comment]
Ye its so aids

**Comment by laikadoggirl** [comment]
And keep in mind the suppressed (other semi rifle, has even less than the assault)

**Comment by TC-DarkSlayer** [comment]
Wait why did you make howitzer shell cost steel ingots

**Comment by laikadoggirl** [comment]
I dont remember that

**Comment by HolySSSS** [comment]
> good luck getting vamist to accept a pr that goes against #votes

image
This is a questionable vote.
A bit, but sure.

**Comment by laikadoggirl** [comment]
In the assembler maybe, but I would've never done it in bomb shop, I'm a strong believer artillery needs a buff not a nerf

**Comment by laikadoggirl** [comment]
I'm

> > good luck getting vamist to accept a pr that goes against #votes
> 
> image This is a questionable vote. A bit, but sure.

Ye dark is bad at making votes, can't make one without four really close together choices

**Comment by TC-DarkSlayer** [comment]
no 4 for Armor already won
+ also did you keep coal cost for steel on purpose?

**Comment by laikadoggirl** [comment]
> no 4 for Armor already won
> 
> * also did you keep coal cost for steel on purpose?

Ye, it's literally how steel is made

**Comment by TC-DarkSlayer** [comment]
ok just making sure since I agree ye

**Comment by laikadoggirl** [comment]
Also we all know gun update complainers haven't played since the 4x bug, making it a non issue anyway

**Comment by TC-DarkSlayer** [comment]
oh and lol
image

**Comment by laikadoggirl** [comment]
Ye

**Comment by laikadoggirl** [comment]
That's also a non issue though, literally just wasting iron

**Comment by laikadoggirl** [comment]
There is no benefit to making a shotgun room, just mason being mason

**Comment by laikadoggirl** [comment]
It was meant to be good for assembling weapons early game anyway, not once you have 200 iron to put in

**Comment by TC-DarkSlayer** [comment]
just a way to save coins

**Comment by laikadoggirl** [comment]
Ye

**Comment by laikadoggirl** [comment]
But that late in the game coins for the shotgun doesn't matter anyway

**Comment by TC-DarkSlayer** [comment]
image

**Comment by laikadoggirl** [comment]
Ok now change damage for all the other guns like that instead of hitters lol

**Comment by TC-DarkSlayer** [comment]
hmm 50 cal I'm assuming that's pretty stronk so should dmg be 3 hearts instead?

**Comment by laikadoggirl** [comment]
> hmm 50 cal I'm assuming that's pretty stronk so should dmg be 3 hearts instead?

Nah keep it how it is

**Comment by laikadoggirl** [comment]
Realistically 50 cal would be upf sniper tier but that would be aids on tc

**Comment by TC-DarkSlayer** [comment]
I'ma add vanilla crates to TC

oh wait shit, a lot of TC uses old crates like chickenassembler/upf shit

**Comment by laikadoggirl** [comment]
Crak was handled a few prs back

**Comment by TC-DarkSlayer** [comment]
ye it's basically no change this pr has been here for years

**Pull request closed without merging**
