### PR TITLE
Food and Eating

### PR DESCRIPTION
**Pull request by TC-DarkSlayer**
- Food stacks are now merged which would reduce amount of blobs/lag caused by them (for example grain)
- Juggernaut can now use V to eat
- GrainPlant now gives 1-3 grain per plant
- Grain stacks to 10
- A lot of other food now stacks
- Automat no longer targets passive animals
- Pumpkin seed chance no longer random
- Badgers/Bagels drop less meat
- Foodcans now costs 2x as much
- Foodcans now can be sold in bulk
- Extractor increased for more factory possibilities
- Grinding logs gives more wood

### CODE REVIEW

**Comment by laikadoggirl** [comment]
Dark I actually know of this huge bug with eating while stunned, if you patch it out of vanilla kag I'll pay the bounty myself, 50 usd

**Comment by TC-DarkSlayer** [comment]
50 bucks richer

**Comment by laikadoggirl** [comment]
Ye once it gets merged to offi I'll send it

**Comment by TC-DarkSlayer** [comment]
heard it was hard coded and that it is used by only kag sweats that can pull this feat

**Comment by laikadoggirl** [comment]
Yeah that's why I will give the bounty to patch it out, and make kag more
accessible for new players

**Comment by laikadoggirl** [comment]
So that's what happens when I use email replies, wack

**Comment by TC-DarkSlayer** [comment]
Splitting this PR to make it easier on vamist

**Pull request closed without merging**
