### PR TITLE
make artillery great again

### PR DESCRIPTION
**Pull request by laikadoggirl**
buffed howitzer back to its original unshit range
buffed howitzer to destroy dirt now

brought back bombardment
heavily nerfed bombardment from mininukes to howitzer shells
upped price of both bombardments
added fragmentation mine drop to the chicken phone because mines = !!FUN!!

### CODE REVIEW

**Comment by laikadoggirl** [comment]
oh also was balance verified by ginger

**Comment by Gingerbeard5773** [comment]
just a note; Tflippy _was_ going to rebuff howitzers but never got around to it cuz he lazy, so we did it for him

**Comment by Spepbuthewranglesgithub** [comment]
do it flippy, _do it._

**Comment by laikadoggirl** [comment]
damn this bitch aint closed yet?

**Comment by Gingerbeard5773** [comment]
close it pls

**Pull request closed without merging**
