### PR TITLE
Dark guns

### PR DESCRIPTION
**Pull request by TC-DarkSlayer**
- pdw, smg, and ak47 fire rate is nerfed
- autoshotgun, revolver, minigun dmg is nerfed
- carbine, ak47 dmg is buffed
- SAR recoil reduced
- Beagle now uses rifleammo
- weakArmor protection buffed slightly
- Fixed double gramophones bug that lasted for 3 years
Bombshop:
-Frag grenade now costs sulphur
- Flash grenade costs less
- smoke grenade costs more sulphur to prevent spam
Assembler:
- sulphur costs reduced: smallrocket, rocket, gatlingammo
- howitzershell less expensive
- sulphur production less dirt

### CODE REVIEW

**Comment by laikadoggirl** [comment]
do it the normal way 5head instead of fleshhit
just change gun damages as needed not poopoo work around that save time now but make more work in the future

**Comment by Vam-Jam** [comment]
fix errors that came with the new kag update (some errors when running tc) and ill merge

**Comment by TC-DarkSlayer** [comment]
> do it the normal way 5head instead of fleshhit just change gun damages as needed not poopoo work around that save time now but make more work in the future

was just buffing armor in general

**Comment by TC-DarkSlayer** [comment]
ok I see, ballista and vehicle shop is bugged time to fix ;-;

**Comment by laikadoggirl** [comment]
> 
> 
> > do it the normal way 5head instead of fleshhit just change gun damages as needed not poopoo work around that save time now but make more work in the future
> 
> was just buffing armor in general

except that also buffs unarmored, if you are just buffing armor there are less shit ways

**Comment by TC-DarkSlayer** [comment]
> > > do it the normal way 5head instead of fleshhit just change gun damages as needed not poopoo work around that save time now but make more work in the future
> > 
> > 
> > was just buffing armor in general
> 
> except that also buffs unarmored, if you are just buffing armor there are less shit ways

Does not,
I buffed the armor, it's just that armorcode is inside fleshhit.as thanks to goldenguy
Also was thinking of making armor something that actually absorbs the damage
Only thing I changed in fleshhit.as that affects both unarmored and armored is fire damage, doesn't nerf scorching flames, but it reduces how lethal accidentally touching a single flame particle

**Comment by TC-DarkSlayer** [comment]
anyways I fixed the kag update error stuffs
i hope you vamist will do the food update first tho, it fixes a lot of lag from scrubs

**Comment by laikadoggirl** [comment]
> 
> 
> > > > do it the normal way 5head instead of fleshhit just change gun damages as needed not poopoo work around that save time now but make more work in the future
> > > 
> > > 
> > > was just buffing armor in general
> > 
> > 
> > except that also buffs unarmored, if you are just buffing armor there are less shit ways
> 
> Does not, I buffed the armor, it's just that armorcode is inside fleshhit.as thanks to goldenguy Also was thinking of making armor something that actually absorbs the damage Only thing I changed in fleshhit.as that affects both unarmored and armored is fire damage, doesn't nerf scorching flames, but it reduces how lethal accidentally touching a single flame particle

id suggest not a hard absorb, but absorbs a portion (decreases damage taken) until it breaks

also write better commit descriptions then, it seemed at first like you literally just made all flesh take 20% less damage 5head

**Comment by laikadoggirl** [comment]
also unless I missed some massive shartery, nobody actually touched upf weapons fire rates purposefully, either its a relic of the gun update, or kag update shartery, but find out what is actually causing them to be aids before you just straight nerf them, fix it the right way, dont just slap more shitcode on top

**Comment by laikadoggirl** [comment]
also rather than nerfing flame damage, make it burn out quicker instead, that way if you touch a single flame you dont burn to death after it stays for 8 seconds, nerfing its damage is dumb. It would be better at keeping you from burning to death after grazing a meteor, it would also serve to decrease the retarded flame flinch anim, rather than just make it damage you less

**Comment by TC-DarkSlayer** [comment]
I tested PDW and it works good now, before it was actually op
laika you and I know fire damage is actually cancer everyone in TC knows this

**Comment by laikadoggirl** [comment]
> I tested PDW and it works good now, before it was actually op laika you and I know fire damage is actually cancer everyone in TC knows this

Literally no, it's entirely burn time and the on fire anim

**Comment by laikadoggirl** [comment]
It would be fine if it didn't give you that retarded on fire animation, and took half as long to burn out

**Comment by TC-DarkSlayer** [comment]
You think fire isn't op and that it's the burn time that's op?

**Comment by laikadoggirl** [comment]
> You think fire isn't op and that it's the burn time that's op?

Can you read or nah, also what happened to voting on things 🤔

**Comment by TC-DarkSlayer** [comment]
Fire animation I know you're talking about how long someone burns I think it'd be better for the burn time to scale based on how long they've stayed in the fire but then again, fire kills them instantaneously

**Comment by laikadoggirl** [comment]
I also can't believe we went full circle all the way back to being buttmad about oil throwers and trying to nerf them again, kinda funny

**Comment by TC-DarkSlayer** [comment]
oh it was just that scorcher literally shreds I saw hoob got destroyed in 5 seconds

**Comment by TC-DarkSlayer** [comment]
For oil throwers literally that's a waste of precious oil

**Comment by laikadoggirl** [comment]
How much did you decrease flame damage anyway

**Comment by TC-DarkSlayer** [comment]
4.0 to 2.5

**Comment by laikadoggirl** [comment]
2.75 take it or leave it

**Comment by laikadoggirl** [comment]
This is definetly also not because I was working on incendiary mortar shells prior to this pr :trollface:

**Comment by TC-DarkSlayer** [comment]
internet got killed anyways ye suyre was thinking of 3.0 but ill take 2.75 :p

**Comment by laikadoggirl** [comment]
Also considering my last _gift_ to the tc community being an arty update with the incin shells, will most likely add loading gas cans :trollface:

**Comment by TC-DarkSlayer** [comment]
pog mustard gas bomb shell cannon

**Comment by laikadoggirl** [comment]
> pog mustard gas bomb shell cannon

Nah incin and the gas cans are separate, and think bigger bro, pax artillery

**Comment by TC-DarkSlayer** [comment]
laika, were gauss rifles to use steel ingots once again due to it being like the TC community's long lost funny feature, what damage should it do

**Comment by TC-DarkSlayer** [comment]
> > pog mustard gas bomb shell cannon
> 
> Nah incin and the gas cans are separate, and think bigger bro, pax artillery

rippio artillery

**Review by Vam-Jam — APPROVED** [review]

**Comment by laikadoggirl** [comment]
Sorry @TC-DarkSlayer what was your question I can't hear you as this isn't discord where you very rudely blocked me

**Pull request merged**
